# Generated by Django 5.0.7 on 2024-08-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                ("title", models.CharField(db_index=True, max_length=255, unique=True)),
                ("studios", models.CharField(db_index=True, max_length=255)),
                ("producers", models.CharField(db_index=True, max_length=255)),
                ("winner", models.CharField(db_index=True, max_length=10)),
            ],
        ),
    ]
